[build]
  # Build command
  command = "npm run build"
  
  # Directory with the static files
  publish = "dist"

[[redirects]]
  # Redirect all routes to index.html for SPA
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node version
  NODE_VERSION = "18"

[[headers]]
  # Headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Headers for static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"